# Generated by Django 4.2.20 on 2026-09-08 15:30

from django.db import migrations, models
import vc_pairs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.FileField(upload_to=vc_pairs.models._pair_path)),
                ('visualization', models.FileField(blank=True, null=True, upload_to=vc_pairs.models._pair_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('visualization_name', models.CharField(blank=True, max_length=255)),
                ('total_frames', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('fps', models.FloatField(default=0.0)),
                ('chunk_size', models.PositiveIntegerField(default=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'видео-пара',
                'verbose_name_plural': 'видео-пары',
            },
        ),
    ]
