# Generated by Django 4.2.20 on 2026-09-08 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vc_pairs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fragment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marker_fragments', to=settings.AUTH_USER_MODEL)),
                ('video_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fragments', to='vc_pairs.videopair')),
            ],
            options={
                'verbose_name': 'фрагмент',
                'verbose_name_plural': 'фрагменты',
                'ordering': ['start', 'end'],
            },
        ),
    ]
