# Generated by Django 4.2.30 on 2026-09-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vc_fragments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fragment',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
